### PR TITLE
Record span of assignment operator

### PR DESCRIPTION
**Pull request by ayazhafiz**
Needed for a linter I will add to emit warnings when "=" and ":=" are
mixed.

ptal @luke-bhan

### CODE REVIEW

**Comment by lukebhan** [comment]
So, then we are going back from what you had wrote with using the = and := as switches of each other depending on the user param and just defining this right?

**Review by lukebhan — APPROVED** [review]

**Comment by ayazhafiz** [comment]
What do you think? Right now they will still be emitted as only = or only :=, but we can remove that option.

**Comment by lukebhan** [comment]
I think we should be explicit on those operators. So only one can be used in a program and leave it up to the users. (aka i like the way we have it, I was just making sure that was the intention)

**Comment by ayazhafiz** [comment]
Hm I guess I'm confused. Right now if you do

```
a = 1
b := 1
```

it will be accepted but emit as

```
a=1
b=1
```

or the same with all :=. Is this okay? I plan to add a lint after this commit that will warn when = and := are mixed.

**Comment by lukebhan** [comment]
Oh ok, I thought the linter was already there. I don't think thats ok without saying something to the user, but if you write the linter then its fine, because otherwise maybe the user has defined one as const def and the other as def and thus that could confused them without a warning.

**Comment by ayazhafiz** [comment]
sounds good

**Pull request merged**
