### PR TITLE
Use \mod for mod emit in latex and wrap latex emit as inline math

### PR DESCRIPTION
**Pull request by ayazhafiz**
cc @timothycobrien

### CODE REVIEW

**Comment by ayazhafiz** [comment]
done

**Comment by timothycobrien** [comment]
@ayazhafiz I believe there shouldn't be a `\` before characters such as `(` or `)` (see file [here](https://github.com/yslide/slide/blob/842a531a81beac8bf5ae5808060bbbe687737cbd/slide/src/test/ui/emit/latex/additive_identity_any.slide))

**Comment by ayazhafiz** [comment]
you're right. want to send a patch?

**Comment by timothycobrien** [comment]
Will do

**Comment by timothycobrien** [comment]
Associated exponents are not correct, how should we go about modifying them? @ayazhafiz 

`$2 ^ 3 ^ 2$` errors, for example

**Comment by ayazhafiz** [comment]
Yes, I noticed that too. They will need to be wrapped in braces according to the association. So that example should be `$2 ^ {3 ^ 2}$`.

**Pull request merged**
